// Message types
export const CODESPIN_SAVE_CONNECTION = "CODESPIN_SAVE_CONNECTION";

export const CODESPIN_GET_PROJECTS = "CODESPIN_API_GET_PROJECTS";
export const CODESPIN_GET_PROJECTS_RESPONSE =
  "CODESPIN_API_GET_PROJECTS_RESPONSE";

// Error codes
export const UNAUTHORIZED = "UNAUTHORIZED";
export const MISSING_KEY = "MISSING_KEY";
